apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: worker-resiliency
scopes:
  - terravibes-worker
spec:
  policies:
    timeouts:
      opExecution: 3h  # should be bigger than any individual op run
    retries:
      workerRetry:
        policy: constant
        duration: 60s
        maxRetries: -1
  targets:
    components:
      control-pubsub:
        inbound:
          retry: "workerRetry"
          timeout: "opExecution"
