apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: control-pubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    secretKeyRef:
      name: rabbitmq-connection-string
      key: rabbitmq-connection-string
  - name: backOffMaxRetries
    value: -1
  - name: publisherConfirm
    value: "true"
  - name: requeueInFailure
    value: "true"
  - name: deliveryMode
    value: "2"
  - name: prefetchCount
    value: 0
  - name: deletedWhenUnused
    value: "false"
