# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/farmai/terravibes/services-base:12380

COPY src /app/src
COPY workflows /app/workflows
COPY ops /app/ops

RUN /opt/conda/bin/pip install /app/src/vibe_core && \
    /opt/conda/bin/pip install /app/src/vibe_common && \
    /opt/conda/bin/pip install /app/src/vibe_agent
 
RUN rm -rf /app/src

RUN find /app -type d -name __pycache__ | xargs rm -rf

EXPOSE 3000 3500 50001

WORKDIR /app
