name: Additional information
description: Request for additional information related to FarmVibes.AI 
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to reach us! Feel free to ask any question related to FarmVibes.AI, we will get back to you as soon as possible.

  - type: dropdown
    id: info-topic
    attributes:
      label: Topic
      multiple: true
      options:
        - General question
        - Feature request
        - Documentation
        - FarmVibes.AI setup
        - Management script
        - Notebook
        - Workflow
        - Local cluster
        - Remote (AKS) cluster
    validations:
      required: false

  - type: textarea
    id: info-request
    attributes:
      label: Ask away! 
      placeholder: |
        Let us know what is on your mind...
    validations:
      required: true
