apiVersion: v1
kind: Secret
metadata:
  name: redis
  labels:
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  redis-password: {{ .Values.redis.password | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: redis
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  serviceName: redis-headless
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: {{ required "redis.image is required" .Values.redis.image | quote }}
          imagePullPolicy: IfNotPresent
          args:
            - --appendonly
            - "no"
            - --requirepass
            - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  rabbitmq-password: {{ .Values.rabbitmq.password | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: rabbitmq
  ports:
    - name: epmd
      port: 4369
      targetPort: epmd
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: dist
      port: 25672
      targetPort: dist
    - name: http-stats
      port: 15672
      targetPort: management
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: dist
      port: 25672
      targetPort: dist
    - name: http-stats
      port: 15672
      targetPort: management
    - name: epmd
      port: 4369
      targetPort: epmd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  serviceName: rabbitmq-headless
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      automountServiceAccountToken: false
      containers:
        - name: rabbitmq
          image: {{ required "rabbitmq.image is required" .Values.rabbitmq.image | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: -rabbit consumer_timeout 10800000
          ports:
            - name: amqp
              containerPort: 5672
            - name: dist
              containerPort: 25672
            - name: management
              containerPort: 15672
            - name: epmd
              containerPort: 4369
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage }}
