apiVersion: apps/v1
kind: Deployment
metadata:
  name: terravibes-cache
  labels:
    app: terravibes-cache
    backend: terravibes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terravibes-cache
  template:
    metadata:
      labels:
        app: terravibes-cache
        backend: terravibes
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "terravibes-cache"
        dapr.io/app-port: "3000"
        dapr.io/app-protocol: "http"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
        dapr.io/log-level: "debug"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: terravibes-cache
          image:  mcr.microsoft.com/farmai/terravibes/cache:latest
          workingDir: /tmp
          securityContext:
            runAsUser: $USER_ID
            runAsGroup: $GROUP_ID
          command:
            - sh
            - -c
            - "/opt/conda/bin/vibe-cache cache.impl.port=3000 \
               cache.impl.logdir=/mnt/logs"
          env:
          - name: DAPR_API_METHOD_INVOCATION_PROTOCOL
            value: HTTP
          - name: BLOB_CONTAINER_NAME
            value: ppe-assets-fan
          - name: STAC_COSMOS_URI_SECRET
            value: dummy
          - name: STAC_CONTAINER_NAME_SECRET
            value: dummy
          - name: STAC_COSMOS_DATABASE_NAME_SECRET
            value: dummy
          - name: STAC_COSMOS_CONNECTION_KEY_SECRET
            value: dummy
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /mnt/
              name: host-mount
          imagePullPolicy: Always
      volumes:
          - name: host-mount
            hostPath:
                path: /mnt/
