kind: Service
apiVersion: v1
metadata:
  name: terravibes-rest-api
  labels:
    app: terravibes-rest-api
    backend: terravibes
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30000
    port: 3000
  selector:
    app: terravibes-rest-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terravibes-rest-api
  labels:
    app: terravibes-rest-api
    backend: terravibes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terravibes-rest-api
      backend: terravibes
  template:
    metadata:
      labels:
        app: terravibes-rest-api
        backend: terravibes
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "terravibes-rest-api"
        dapr.io/app-port: "3000"
        dapr.io/app-protocol: "http"
        dapr.io/log-level: "debug"
        dapr.io/log-as-json: "true"
    spec:
      volumes:
        - name: terravibes
          hostPath:
            path: /mnt
      containers:
        - name: terravibes-rest-api
          image: mcr.microsoft.com/farmai/terravibes/api-orchestrator:latest
          workingDir: /tmp
          securityContext:
            runAsUser: $USER_ID
            runAsGroup: $GROUP_ID
          command:
            - sh
            - -c
            - "/opt/conda/bin/vibe-server --port 3000 \
               --terravibes-host-assets-dir FARMVIBES_AI_HOST_ASSETS_DIR \
               --logdir=/mnt/logs"
          env:
          - name: DAPR_API_METHOD_INVOCATION_PROTOCOL
            value: HTTP
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          volumeMounts:
            - name: terravibes
              mountPath: /mnt
