apiVersion: apps/v1
kind: Deployment
metadata:
  name: terravibes-worker
  labels:
    app: terravibes-worker
    backend: terravibes
spec:
  replicas: REPLICAS_TO_BE_REPLACED
  selector:
    matchLabels:
      app: terravibes-worker
  template:
    metadata:
      labels:
        app: terravibes-worker
        backend: terravibes
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "terravibes-worker"
        dapr.io/config: "sidecar-config"
        dapr.io/app-max-concurrency: "1"  # only one message processed at a time
        dapr.io/app-port: "3000"
        dapr.io/app-protocol: "http"
        dapr.io/log-level: "debug"
        dapr.io/log-as-json: "true"
        dapr.io/enable-app-health-check: "true"
        dapr.io/app-health-check-path: "/health"
    spec:
      volumes:
        - name: terravibes
          hostPath:
            path: /mnt
      containers:
        - name: terravibes-worker
          image: mcr.microsoft.com/farmai/terravibes/worker:latest
          workingDir: /tmp
          securityContext:
            runAsUser: $USER_ID
            runAsGroup: $GROUP_ID
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/bin/curl
                  - http://localhost:3000/shutdown
          command:
            - sh
            - -c
            - "/opt/conda/bin/vibe-worker worker.impl.port=3000 \
               worker.impl.control_topic=commands \
               worker.impl.logdir=/mnt/logs \
               worker.impl.factory_spec.storage.local_path=/mnt/data/stac \
               worker.impl.factory_spec.storage.asset_manager.local_storage_path=/mnt/data/assets"
          env:
          - name: DAPR_API_METHOD_INVOCATION_PROTOCOL
            value: HTTP
          - name: HOME
            value: /tmp
          - name: BLOB_CONTAINER_NAME
            value: ppe-assets-fan
          - name: STAC_COSMOS_URI_SECRET
            value: dummy
          - name: STAC_CONTAINER_NAME_SECRET
            value: dummy
          - name: STAC_COSMOS_DATABASE_NAME_SECRET
            value: dummy
          - name: STAC_COSMOS_CONNECTION_KEY_SECRET
            value: dummy
          imagePullPolicy: Always
          volumeMounts:
            - name: terravibes
              mountPath: /mnt
