apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: control-pubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    secretKeyRef:
      name: rabbitmq-connection-string
      key: rabbitmq-connection-string
  - name: backOffMaxRetries
    value: -1
