name: Build FarmVibes.AI documentation
run-name: Generate documentation html pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Checkout gh-pages
        if: github.event_name != 'pull_request'
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Set up Python 3.11
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.11"

      - name: Install documentation dependencies
        run: |
          pip install --upgrade pip
          pip install ./src/vibe_core
          pip install -r docs/requirements.txt

      - name: Build documentation pages
        run: make -C docs html

      - name: Publish to gh-pages
        if: github.event_name != 'pull_request'
        run: |
          cp -r docs/build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update documentation" -a || true
          git push origin HEAD:gh-pages
